### ISSUE TITLE
Snippet Element does not use specified codename

### ISSUE THREAD

**Issue by msrcodes** [kontent-ai/management-sdk-js#83]
### Brief bug description

When I add a content type with a snippet element, e.g,:

```typescript
builder.snippetElement({
    codename: 'asnippet', // I've specified a codename here
    type: 'snippet',
    snippet: {
        codename: 'greatsnippet',
    },
    content_group: {
        codename: 'groupb',
    },
}),
```

it doesn't get added with the codename that I've specified, and instead generates its own codename based on the name of the Snippet Content Type that I've referenced from snippet.codename:

```json
{
  "snippet": {
    "id": "9a9de080-ae97-464d-a552-abd07af97b6c"
  },
  "type": "snippet",
  "id": "32fdbdb5-93bb-4974-9d54-02170b066d2d",
  "codename": "my_great_snippet", // Note that codename has changed here
  "is_non_localizable": false,
  "content_group": {
    "id":"e490a5e0-2e43-432b-b52e-db2f1a4f8490"
  }
}
```

### Repro steps

1. Add a snippet element to an existing content type:

```typescript
await managementClient.modifyContentType().byTypeCodename(typeCodename).withData({
	op: 'addInto',
	path: '/elements',
	value: snippetElement, // As defined above
}).toPromise()
```

2. Fetch the whole content type

```typescript
await this.managementClient.viewContentType().byTypeCodename(typeCodename).toPromise()
```

3. Observe that the `codename` fields of each do not match

### Expected behavior

When I add an element with a given `codename`, the element should have that `codename`.

### Test environment

 - Platform/OS: MacOS
 - Browser: N/A
 - Version: 3.0.1

### Screenshots

Add links to screenshots, if possible.

**Comment by Enngage** [comment]
Hi @msrcodes,

Thank you for submitting the issue. The reason the codename is not set on snippet element is because it's not actually supported by API:

![snippet](https://user-images.githubusercontent.com/7137351/183384442-7a2a7c7a-f34f-440d-a059-0d48329ac244.png)

In the end, there is actually no "snippet" element as the snippet is replaced by the elements "in" that snippet and the "codename" in this case is just an identifier of the snippet that is embedded in the content type. 

This SDK incorrectly listed the `codename` property which I have now removed and will not be available in next release.

**Comment by msrcodes** [comment]
Fab, thanks for looking into this @Enngage 🚀
