### ISSUE TITLE
Missing a codename property for a snippet element in a content type

### ISSUE THREAD

**Issue by JiriLojda** [kontent-ai/management-sdk-js#90]
### Brief bug description

TS type for a snippet element in a content type is missing a codename property. However, according to [the documentation](https://kontent.ai/learn/reference/management-api-v2/#section/Content-type-snippet-element), the API returns it.

### Repro steps

1. Open the type and see the missing property

### Expected behavior

The property is present

### Test environment

 - Version 3.4.0

**Comment by Nickm615** [comment]
I wanted to clarify this issue. I can see that the view content type endpoint does return the codename of a snippet element, so the issue is just the missing property from ISnippetElementData in models/elements.content-type-element-models.ts?

**Comment by JiriLojda** [comment]
You are correct. The property is missing in the type here. https://github.com/kontent-ai/management-sdk-js/blob/master/lib/models/elements/content-type-element.models.ts#L68-L72 I would even say that the property could be on the shared type (https://github.com/kontent-ai/management-sdk-js/blob/master/lib/models/elements/content-type-element.models.ts#L29-L32), because every element should have a codename.

**Comment by Enngage** [comment]
@JiriLojda The documentation actually misses the `codename` element for `content type snippet element` -> 

![codename_missing](https://user-images.githubusercontent.com/7137351/214011017-2bc29372-7bf1-4dc9-bcc6-6d8e98b2290f.png)

It likely depends on where this codename should be used or maybe the documentation is wrong. 

@Nickm615 can you please investigate whether the `codename` is supported by API and whether the documentation is wrong or whether there is a distinction of models (e.g. when fetching or when updating..)

**Comment by JiriLojda** [comment]
@Enngage You can't specify the codename when creating a new content type. It can only be generated by Kontent.ai. However, if you'd take a look at the response type of the `POST` endpoint or any other content type endpoint, you'd see the codename property.
![Screenshot 2023-01-23 at 11 16 19](https://user-images.githubusercontent.com/25480503/214016248-b11ebcb3-14fd-4c5d-ba29-5f99771dffe8.png)
It is always returned (I believe the documentation has it wrong that it is not marked as required in the response) and you can specify it when modifying a content type, but not when creating one.

**Comment by Nickm615** [comment]
I confirmed the behavior that element codename for a snippet can't be specified when creating a content type.  The response does contain the codename of the snippet element, 
![image](https://user-images.githubusercontent.com/86981780/214148128-d48c16fb-7fc4-470d-9a41-949fce7b00e6.png)
but it is always based on the name/codename of the snippet itself rather than the one specified in the request. As far as I can tell this matches the documentation. When you retrieve a content type using the MAPI, the snippet element always inherits the codename of the snippet its referencing. Additionally, when you query for the type using the REST API rather than the SDK the response is totally different 
![image](https://user-images.githubusercontent.com/86981780/214147830-84595ffe-8a20-4ebb-b43b-c2d3c618e078.png)
I also noticed that in the editor you can't see or edit the codename of a snippet element at all. From my perspective there is some ambiguity around the element, I'm not sure if the intention is for snippet elements to have codenames that can be set like every other element (if so, why aren't they in the editor?) or if the SDK response should instead look like the API response.
I'm hoping to get some clarity before I begin working on any changes to the SDK.

**Comment by JiriLojda** [comment]
You can't edit the codename of a snippet element. That is correct. But the MAPI returns it for the element. The whole point of this issue is for the codename to be accessible when I receive (fetch) elements from MAPI. As you mentioned, the structure of the item variant is different in the raw API response and in the response provided by the SDK. That is fine, but the response provided by the SDK should give me the codename as well, which is not the case at the moment. (At least not according to the TypeScript definition.)
I don't think it matters how Kontent.ai generates the codename (i.e. that it is the codename of the snippet inside the element). It is some string identifying the element.
